// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaletteStudioApi.Data;

#nullable disable

namespace PaletteStudioApi.Data.PaletteStudioMigrations
{
    [DbContext(typeof(PaletteStudioDbContext))]
    [Migration("20230510221615_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("PaletteStudioApi.Models.Colour", b =>
                {
                    b.Property<string>("HexCode")
                        .HasColumnType("TEXT");

                    b.HasKey("HexCode");

                    b.ToTable("Colours");

                    b.HasData(
                        new
                        {
                            HexCode = "#000000"
                        },
                        new
                        {
                            HexCode = "#FFFFFF"
                        },
                        new
                        {
                            HexCode = "#9B111E"
                        },
                        new
                        {
                            HexCode = "#89AC76"
                        },
                        new
                        {
                            HexCode = "#F3A505"
                        },
                        new
                        {
                            HexCode = "#5D9B9B"
                        },
                        new
                        {
                            HexCode = "#4C9141"
                        },
                        new
                        {
                            HexCode = "#B44C43"
                        },
                        new
                        {
                            HexCode = "#3E5F8A"
                        },
                        new
                        {
                            HexCode = "#F80000"
                        },
                        new
                        {
                            HexCode = "#8B8C7A"
                        });
                });

            modelBuilder.Entity("PaletteStudioApi.Models.ColourGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColourHexCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaletteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundColourHexCode");

                    b.HasIndex("PaletteId");

                    b.ToTable("ColourGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundColourHexCode = "#FFFFFF",
                            PaletteId = 1
                        },
                        new
                        {
                            Id = 2,
                            BackgroundColourHexCode = "#F3A505",
                            PaletteId = 1
                        },
                        new
                        {
                            Id = 3,
                            BackgroundColourHexCode = "#F80000",
                            PaletteId = 2
                        },
                        new
                        {
                            Id = 4,
                            BackgroundColourHexCode = "#000000",
                            PaletteId = 3
                        },
                        new
                        {
                            Id = 5,
                            BackgroundColourHexCode = "#8B8C7A",
                            PaletteId = 3
                        });
                });

            modelBuilder.Entity("PaletteStudioApi.Models.ForegroundColour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColourGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColourHexCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColourGroupId");

                    b.HasIndex("ColourHexCode");

                    b.ToTable("ForegroundColours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColourGroupId = 1,
                            ColourHexCode = "#9B111E"
                        },
                        new
                        {
                            Id = 2,
                            ColourGroupId = 1,
                            ColourHexCode = "#F80000"
                        },
                        new
                        {
                            Id = 3,
                            ColourGroupId = 1,
                            ColourHexCode = "#8B8C7A"
                        },
                        new
                        {
                            Id = 4,
                            ColourGroupId = 1,
                            ColourHexCode = "#4C9141"
                        },
                        new
                        {
                            Id = 5,
                            ColourGroupId = 3,
                            ColourHexCode = "#B44C43"
                        },
                        new
                        {
                            Id = 6,
                            ColourGroupId = 3,
                            ColourHexCode = "#000000"
                        },
                        new
                        {
                            Id = 7,
                            ColourGroupId = 3,
                            ColourHexCode = "#F3A505"
                        },
                        new
                        {
                            Id = 8,
                            ColourGroupId = 4,
                            ColourHexCode = "#3E5F8A"
                        },
                        new
                        {
                            Id = 9,
                            ColourGroupId = 4,
                            ColourHexCode = "#F3A505"
                        },
                        new
                        {
                            Id = 10,
                            ColourGroupId = 5,
                            ColourHexCode = "#9B111E"
                        });
                });

            modelBuilder.Entity("PaletteStudioApi.Models.Palette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Palettes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Palette 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Palette 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Palette 3"
                        });
                });

            modelBuilder.Entity("PaletteStudioApi.Models.ColourGroup", b =>
                {
                    b.HasOne("PaletteStudioApi.Models.Colour", "BackgroundColour")
                        .WithMany("ColourGroups")
                        .HasForeignKey("BackgroundColourHexCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PaletteStudioApi.Models.Palette", "Palette")
                        .WithMany("ColourGroups")
                        .HasForeignKey("PaletteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackgroundColour");

                    b.Navigation("Palette");
                });

            modelBuilder.Entity("PaletteStudioApi.Models.ForegroundColour", b =>
                {
                    b.HasOne("PaletteStudioApi.Models.ColourGroup", "ColourGroup")
                        .WithMany("ForegroundColours")
                        .HasForeignKey("ColourGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaletteStudioApi.Models.Colour", "Colour")
                        .WithMany("ForegroundColours")
                        .HasForeignKey("ColourHexCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colour");

                    b.Navigation("ColourGroup");
                });

            modelBuilder.Entity("PaletteStudioApi.Models.Colour", b =>
                {
                    b.Navigation("ColourGroups");

                    b.Navigation("ForegroundColours");
                });

            modelBuilder.Entity("PaletteStudioApi.Models.ColourGroup", b =>
                {
                    b.Navigation("ForegroundColours");
                });

            modelBuilder.Entity("PaletteStudioApi.Models.Palette", b =>
                {
                    b.Navigation("ColourGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
